version: '3.7'

services:
    db-wtc:
        build:
            context: .
            dockerfile: Dockerfile-db
        container_name: cont-db-wtc
        restart: unless-stopped
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            POSTGRES_USER: admin_wtc
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: db_wtc
        volumes:
          - db_data:/var/lib/postgres/data
        networks:
            - wtc-network

    wtc:
        depends_on:
            - db-wtc
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cont-wtc
        ports:
            - 8080:8080
        expose:
            - 8080
        environment:
            SPRING_DATASOURCE_USERNAME: admin_wtc
            SPRING_DATASOURCE_PASSWORD: 123
            SPRING_DATASOURCE_URL: jdbc:postgresql://db-wtc:5432/db_wtc
        networks:
            - wtc-network

networks:
    wtc-network:

volumes:
    db_data:
